import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
                                    {/*тут был только inter.className*/}
      <body className={`{inter.className} h-screen overflow-hidden`}>
      <Navbar />
                                               {/*тут было 300px и не было h-full*/}
      <div className='grid grid-cols-1 sm:grid-cols-[250px,1fr] h-full'>
          <Sidebar />
          {children}
      </div>
      </body>
    </html>
  );
}
